name: Deploy Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps & Build
        run: |
          npm ci
          npm run build
        working-directory: code/frontend
      - name: Deploy to Checkdomain via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ${{ secrets.CHECKDOMAIN_FTP_HOST }}
          username: ${{ secrets.CHECKDOMAIN_FTP_USER }}
          password: ${{ secrets.CHECKDOMAIN_FTP_PASSWORD }}
          local-dir: code/frontend/dist/
          server-dir: ${{ secrets.CHECKDOMAIN_FTP_REMOTE_PATH }}
        env:
          TZ: 'Europe/Berlin'
